import TaskStatus from 'enums/TaskStatus';
import { Task } from 'types/Task';

import { Project } from '../types/Project';

export const projects: Project[] = [
  {
    created_by: 'Merv',
    id: '1',
    is_active: true,
    name: 'Project Tracker',
    tasks: [
      {
        assignee_user_id: 'Merv Tampus',
        created_by: 'Merv',
        description: 'Create Project Page',
        due_date: '2022-10-23T13:42:18.631208Z',
        id: '1',
        name: 'Project Page FE',
        project_id: '1',
        status: TaskStatus.IN_PROGRESS,
      },
    ],
  },
  {
    created_by: 'Ferlie',
    id: '2',
    is_active: true,
    name: 'Empath',
    tasks: [
      {
        assignee_user_id: 'Merv Tampus',
        created_by: 'Merv',
        description: 'Create Empath Consent Form',
        due_date: '2022-10-23T13:42:18.631208Z',
        id: '1',
        name: 'Consent Form FE',
        project_id: '2',
        status: TaskStatus.DONE,
      },
      {
        assignee_user_id: 'Merv Tampus',
        created_by: 'Merv',
        description: 'Create Empath Consent Form',
        id: '2',
        name: 'Consent Form BE',
        project_id: '2',
        status: TaskStatus.DONE,
      },
    ],
  },
  {
    created_by: 'Ezra',
    id: '3',
    is_active: true,
    name: 'Enhance CRM',
    tasks: [
      {
        assignee_user_id: 'Merv Tampus',
        created_by: 'Merv',
        description: 'Add sidebar sub items',
        due_date: '2022-10-23T13:42:18.631208Z',
        id: '1',
        name: 'Side Bar Sub Items FE',
        project_id: '3',
        status: TaskStatus.TO_DO,
      },
      {
        assignee_user_id: 'Merv Tampus',
        created_by: 'Merv',
        description: 'Add search button',
        due_date: '2022-10-23T13:42:18.631208Z',
        id: '2',
        name: 'Event Participants Search Button',
        project_id: '3',
        status: TaskStatus.TO_DO,
      },
      {
        assignee_user_id: 'Merv Tampus',
        created_by: 'Merv',
        description: 'Add event participants list',
        due_date: '2022-10-23T13:42:18.631208Z',
        id: '3',
        name: 'Event Participants List FE',
        project_id: '3',
        status: TaskStatus.TO_DO,
      },
    ],
  },
  {
    created_by: 'Raven',
    id: '4',
    is_active: true,
    name: 'Symph OS V2',
    tasks: [
      {
        assignee_user_id: 'Merv Tampus',
        created_by: 'Merv',
        description: 'Add Project Logo Component Backend',
        id: '1',
        name: 'Project Logo BE',
        project_id: '4',
        status: TaskStatus.TO_DO,
      },
    ],
  },
];

export const tasks: Task[] = [
  {
    assignee_user_id: 'Merv Tampus',
    created_by: 'Merv',
    description: 'Create Project Page',
    due_date: '2022-10-23T13:42:18.631208Z',
    id: '1',
    name: 'Project Page FE',
    project_id: '1',
    status: TaskStatus.IN_PROGRESS,
  },
  {
    assignee_user_id: 'Merv Tampus',
    created_by: 'Merv',
    description: 'Create Empath Consent Form',
    due_date: '2022-10-23T13:42:18.631208Z',
    id: '2',
    name: 'Consent Form FE',
    project_id: '2',
    status: TaskStatus.DONE,
  },
  {
    assignee_user_id: 'Merv Tampus',
    created_by: 'Merv',
    description: 'Create Empath Consent Form',
    id: '3',
    name: 'Consent Form BE',
    project_id: '2',
    status: TaskStatus.DONE,
  },
  {
    assignee_user_id: 'Merv Tampus',
    created_by: 'Merv',
    description: 'Add sidebar sub items',
    due_date: '2022-10-23T13:42:18.631208Z',
    id: '4',
    name: 'Side Bar Sub Items FE',
    project_id: '3',
    status: TaskStatus.TO_DO,
  },
  {
    assignee_user_id: 'Merv Tampus',
    created_by: 'Merv',
    description: 'Add search button',
    due_date: '2022-10-23T13:42:18.631208Z',
    id: '5',
    name: 'Event Participants Search Button',
    project_id: '3',
    status: TaskStatus.TO_DO,
  },
  {
    assignee_user_id: 'Merv Tampus',
    created_by: 'Merv',
    description: 'Add event participants list',
    due_date: '2022-10-23T13:42:18.631208Z',
    id: '6',
    name: 'Event Participants List FE',
    project_id: '3',
    status: TaskStatus.TO_DO,
  },
  {
    assignee_user_id: 'Merv Tampus',
    created_by: 'Merv',
    description: 'Add Project Logo Component Backend',
    id: '7',
    name: 'Project Logo BE',
    project_id: '4',
    status: TaskStatus.TO_DO,
  },
];
